# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.env.enable
    config.vm.box = ENV['VG_BOX']
    config.vm.hostname = ENV['VG_HOSTNAME']

    config.vm.synced_folder ENV['VG_SYNCED_FOLDER_ORG'], ENV['VG_SYNCED_FOLDER_DST']

    config.vm.provider "virtualbox" do |v|
        v.memory = ENV['VG_MEMORY']
        v.name = ENV['VG_NAME']
        v.cpus = 2
    end

    config.vm.provision "file", source: "../../config/debian/config/gitconfig", destination: "/tmp/gitconfig"
    config.vm.provision "file", source: "../../config/debian/config/bashrc", destination: "/tmp/bashrc"
    config.vm.provision "file", source: "../../config/debian/config/bash_aliases", destination: "/tmp/bash_aliases"

    config.vm.provision "shell", path: "../../config/debian/sh/bash.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/default.sh"
    # config.vm.provision "shell", path: "../../config/debian/sh/homebrew.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/locale.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/vim.sh"
    # config.vm.provision "shell", path: "../../config/debian/sh/nginx.sh"
    # config.vm.provision "shell", path: "../../config/debian/sh/docker.sh"
    # config.vm.provision "shell", path: "../../config/debian/sh/docker-compose.sh"
    # config.vm.provision "shell", path: "../../config/debian/sh/docker-container.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/nodejs.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/angular.sh"

    config.vm.provision "shell", inline: <<-SHELL
        ip a | ccze -A
    SHELL
end
