# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.env.enable
    config.vm.box = ENV['VG_BOX']
    config.vm.hostname = ENV['VG_HOSTNAME']

    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
        run: "always",
        inline: "ifconfig " + ENV["VG_NETWORK_TYPE"] + " " + ENV["VG_STATIC_IP"] +" netmask " + ENV["VG_NETMASK"] + " up"
    config.vm.provision "shell",
        run: "always",
        inline: "route add default gw " + ENV["VG_GATEWAY"]

    config.vm.synced_folder ENV['VG_SYNCED_FOLDER_ORG'], ENV['VG_SYNCED_FOLDER_DST']

    config.vm.provider "virtualbox" do |v|
        v.memory = ENV['VG_MEMORY']
        v.name = ENV['VG_HOSTNAME']
        v.cpus = ENV['VG_CPUS']
    end

    config.vm.provision "file", source: "../data/config/gitconfig", destination: "/tmp/gitconfig"
    config.vm.provision "file", source: "../data/config/bashrc", destination: "/tmp/bashrc"
    config.vm.provision "file", source: "../data/config/bash_aliases", destination: "/tmp/bash_aliases"

    config.vm.provision "shell", path: "../data/sh/bash.sh"
    config.vm.provision "shell", path: "../data/sh/default.sh"
    config.vm.provision "shell", path: "../data/sh/nginx.sh"
    config.vm.provision "shell", path: "../data/sh/docker.sh"
    config.vm.provision "shell", path: "../data/sh/docker-compose.sh"
    config.vm.provision "shell", path: "../data/sh/docker-container.sh"

    config.vm.provision "shell", inline: <<-SHELL
        ip a | ccze -A
    SHELL
end
