# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.env.enable
    config.vm.box = ENV['VG_BOX']
    config.vm.hostname = ENV['VG_HOSTNAME']

    config.vm.synced_folder ENV['VG_SYNCED_FOLDER_ORG'], ENV['VG_SYNCED_FOLDER_DST']
    config.vm.synced_folder ENV['NGINX_CONF_SRC'], ENV['NGINX_CONF_DST']
#     config.vm.network "forwarded_port", guest: 9000, host: 9000
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 9000, host: 9000
    config.vm.network "forwarded_port", guest: 5432, host: 5432
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.network "forwarded_port", guest: 8008, host: 8008
    config.vm.network "forwarded_port", guest: 8001, host: 8001

    config.vm.provider "virtualbox" do |v|
        v.memory = ENV['VG_MEMORY']
        v.name = ENV['VG_NAME']
        v.cpus = 2
    end

    config.vm.provision "file", source: "../../config/debian/config/gitconfig", destination: "/tmp/gitconfig"
    config.vm.provision "file", source: "../../config/debian/config/bashrc", destination: "/tmp/bashrc"
    config.vm.provision "file", source: "../../config/debian/config/bash_aliases", destination: "/tmp/bash_aliases"
    config.vm.provision "file", source: "../../config/debian/config/shell", destination: "/tmp/shell"
    config.vm.provision "file", source: ENV['SSH_PATH'], destination: "/tmp/ssh"

    config.vm.provision "shell", path: "../../config/debian/sh/bash.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/default.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/homebrew.sh"
    # config.vm.provision "shell", path: "../../config/debian/sh/locale.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/vim.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/nginx.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/docker_ubuntu.sh"
    # config.vm.provision "shell", path: "../../config/debian/sh/docker-compose.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/docker-container.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/nodejs.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/angular.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/motd.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/shell.sh"
    config.vm.provision "shell", path: "../../config/debian/sh/ssh.sh"

    config.vm.provision "shell", inline: <<-SHELL
        ip a | ccze -A
    SHELL
end
