# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.env.enable
    config.vm.box = ENV['VG_BOX']
    config.vm.hostname = ENV['VG_HOSTNAME']

    config.vm.network "public_network", auto_config: false
    config.vm.provision "shell",
        run: "always",
        inline: "ifconfig eth0 10.75.11.172 netmask 255.255.255.0 up"
    config.vm.provision "shell",
        run: "always",
        inline: "route add default gw 10.75.11.254"

    config.vm.synced_folder ENV['VG_SYNCED_FOLDER_ORG'], ENV['VG_SYNCED_FOLDER_DST'], type: "smb",
    smb_username: ENV['VG_SMB_USERNAME'],
    smb_password: ENV['VG_SMB_PASSWORD'],
    mount_options: ["username=" + ENV['VG_SMB_USERNAME'],"password=" + ENV['VG_SMB_PASSWORD']]

    config.vm.provider "virtualbox" do |v|
        v.memory = ENV['VG_MEMORY']
        v.vmname = ENV['VG_HOSTNAME']
    end

    config.vm.provision "file", source: "../../config/centos/config/gitconfig", destination: "/tmp/gitconfig"
    config.vm.provision "file", source: "../../config/centos/config/bashrc", destination: "/tmp/bashrc"
    config.vm.provision "file", source: "../../config/centos/config/bash_aliases", destination: "/tmp/bash_aliases"

    config.vm.provision "shell", path: "../../config/centos/sh/bash.sh"
    config.vm.provision "shell", path: "../../config/centos/sh/default.sh"
    config.vm.provision "shell", path: "../../config/centos/sh/nginx.sh"
    config.vm.provision "shell", path: "../../config/centos/sh/docker.sh"
    config.vm.provision "shell", path: "../../config/centos/sh/docker-compose.sh"
    config.vm.provision "shell", path: "../../config/centos/sh/docker-container.sh"

    config.vm.provision "shell", inline: <<-SHELL
        ip a | ccze -A
    SHELL
end
